name: SonarQube Exporter Workflow

# This workflow responsible for running SonarQube exporter.
#
# Docs - https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube
#
# Make sure to configure the following secrets:
#
# OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN - The SonarQube API token
# OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID - The SonarQube organization ID
# OCEAN__INTEGRATION__CONFIG__SONAR_URL - The SonarQube URL e.g. https://sonarcloud.io
# OCEAN__PORT__CLIENT_ID - Your PORT CLIENT ID
# OCEAN__PORT__CLIENT_SECRET - Your POST CLIENT SECRET

on:
  workflow_dispatch:

jobs:
  run-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          image: port-labs/port-ocean-sonarqube:latest
          options: |
            -i --platform=linux/amd64
            -e OCEAN__EVENT_LISTENER='{"type":"ONCE"}'
            -e OCEAN__PORT__CLIENT_ID=${{ secrets.OCEAN__PORT__CLIENT_ID }}
            -e OCEAN__PORT__CLIENT_SECRET=${{ secrets.OCEAN__PORT__CLIENT_SECRET }}
            -e OCEAN__PORT__BASE_URL=${{ secrets.OCEAN__PORT__BASE_URL }}
            -e OCEAN__INTEGRATION__CONFIG__SONAR_URL=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_URL }}
            -e OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN }}
            -e OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID }}
