name: SonarQube Exporter Workflow

# Docs - https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/code-quality-security/sonarqube
# Make sure to configure the following secrets
# Secrets:
# OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN - The SonarQube API token
# OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID - The SonarQube organization ID
# OCEAN__INTEGRATION__CONFIG__SONAR_URL - The SonarQube URL e.g. https://sonarcloud.io
# OCEAN__PORT__CLIENT_ID - Your PORT CLIENT ID
# OCEAN__PORT__CLIENT_SECRET - Your POST CLIENT SECRET

on:
  workflow_dispatch:

jobs:
  run-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Run Sonarqube Integration
        run: |
          # Set Docker image and run the container
          integration_type="sonarqube"
          version="latest"

          image_name="ghcr.io/port-labs/port-ocean-$integration_type:$version"

          docker run -i --rm --platform=linux/amd64 \
            -e OCEAN__EVENT_LISTENER='{"type":"ONCE"}' -e OCEAN__INITIALIZE_PORT_RESOURCES=true -e OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_API_TOKEN }} -e OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_ORGANIZATION_ID }} -e OCEAN__INTEGRATION__CONFIG__SONAR_URL=${{ secrets.OCEAN__INTEGRATION__CONFIG__SONAR_URL }} -e OCEAN__PORT__CLIENT_ID=${{ secrets.OCEAN__PORT__CLIENT_ID }} -e OCEAN__PORT__CLIENT_SECRET=${{ secrets.OCEAN__PORT__CLIENT_SECRET }} $image_name
